#pragma once

#include <QApplication>
#include <QPushButton>
#include <QPainter>
#include <QMainWindow>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QResizeEvent>
#include <QSpacerItem>
#include <QLabel>
#include <QMessageBox>
#include <QMovie>
#include <QMediaPlayer>
#include <QAudioOutput>
#include <QGraphicsOpacityEffect>
#include <QPropertyAnimation>
#include <QSequentialAnimationGroup>
#include <QFile>
#include <QTimer>
